### ISSUE TITLE
Userless Application Login?

### ISSUE THREAD

**Issue by ccrama** [KirkBushman/Android-Reddit-OAuth2#1]
Came across ARAW and I'm very happy someone is actively working on a replacement for JRAW, which hasn't been updated in some time!

I've been replacing my JRAW implementations with ARAW and noticed that it appears Userless authentication is not supported. Is this something planned, or would a PR to add this in be accepted? 

The only difference from scriptless is the grant_type should be the string `https://oauth.reddit.com/grants/installed_client` and there should be a `device_id` field with a UUID of the device (I would randomize it, personally, to stop user tracking by Reddit).

Thanks!

**Comment by KirkBushman** [comment]
Hi, I don't know why but I didn't see a notification for this issue, sorry for the late response. 
Userless auth was on my mind and I was working on this last week.

The last commit I pushed out fixed this, so you can check it out.
Tell me if it works on your end, I still need to update ARAW.

**Comment by KirkBushman** [comment]
Userless mode is available in the latest release of ARO2 (1.2.0) and working in araw in the second beta.
Closing this for now.
