### ISSUE TITLE
where is authClient being initialized in the README?

### ISSUE THREAD

**Issue by lmj0011** [KirkBushman/Android-Reddit-OAuth2#2]
> The manager object we built in step 1 will provide the url: browser.loadUrl(authClient.provideAuthorizeUrl())

is `authClient` and `manager` the same thing? 

ie.) `val manager = RedditAuth.Builder()` == `authClient` ??

**Comment by KirkBushman** [comment]
Yes, you are right, they are the same object.
I copied code and tweaked it to make it prettier, I must have missed that.
